name: MLflow CI - Build Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11

    - name: Install MLflow
      shell: bash -l {0}
      run: pip install mlflow

    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        cd MLProject
        mlflow run .

    - name: Build Docker Image
      shell: bash -l {0}
      run: |
        cd MLProject
        RUN_ID=$(ls mlruns/*/*/meta.yaml | awk -F'/' '{print $(NF-1)}' | head -n 1)
        echo "RUN_ID=$RUN_ID"

        mlflow models build-docker \
          -m runs:/$RUN_ID/model \
          -n ${{ secrets.DOCKER_USERNAME }}/insurance-mlflow \
          --enable-mlserver

    - name: Push Docker Image
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker push ${{ secrets.DOCKER_USERNAME }}/insurance-mlflow
